name: publish package

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: macos-12
    permissions:
      contents: read
      packages: write
    steps:
      - name: Download Artifact
        id: download-artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          name: artifact-upload-test
          search_artifacts: true
          workflow: build.yml

      - uses: actions/checkout@v3
      # Setup .npmrc file to publish to GitHub Packages
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      # - run: npm install

      - run: cd output && npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
